Repository WordPress/twentytwentytwo, pull requests merged in 2021-12, with the labels that each got.

#275 Try a subtle opacity change on button hovers
  style.css
Labels: [Type] Enhancement

#276 Update birds video
  assets/videos/birds.mp4
Labels: [Type] Enhancement

#277 Use get_theme_file_path to load block patterns
  inc/block-patterns.php
Labels: [Type] Enhancement, [Component] Block Patterns

#279 Try adding a hover state for navigation items
  style.css
Labels: [Type] Enhancement

#293 Stop using H1 tags for the Site Title when it's in a footer pattern.
  inc/patterns/footer-about-title-logo.php
  inc/patterns/footer-blog.php
  inc/patterns/footer-dark.php
  inc/patterns/footer-default.php
  inc/patterns/footer-query-images-title-citation.php
  inc/patterns/footer-query-title-citation.php
Labels: [Type] Bug, [Component] Block Patterns

#290 Remove unnecessary font weight rule font-weight rule from index and home templates
  inc/patterns/query-default.php
  templates/home.html
  templates/index.html
Labels: [Type] Enhancement

#296 Fix alignment in footer blog pattern
  inc/patterns/footer-blog.php
Labels: [Type] Bug, [Component] Block Patterns

#297 Fix font size variable names for buttons
  style.css
  theme.json
Labels: [Type] Bug

#300 Fix query padding
  style.css
Labels: [Type] Bug

#305 Add static analysis to GitHub Actions workflows
  .github/workflows/lint.yml
  functions.php
  inc/block-patterns.php
  phpstan.neon.dist
Labels: [Type] Code Quality
