Repository WordPress/twentytwentytwo, pull requests merged in 2022-01, with the labels that each got.

#310 Adjust padding to better support theme.json and outer padding
  inc/patterns/footer-about-title-logo.php
  inc/patterns/footer-blog.php
  inc/patterns/footer-dark.php
  inc/patterns/footer-default.php
  inc/patterns/footer-logo.php
  inc/patterns/footer-navigation-copyright.php
  inc/patterns/footer-navigation.php
  inc/patterns/footer-query-images-title-citation.php
  inc/patterns/footer-query-title-citation.php
  inc/patterns/footer-social-copyright.php
  inc/patterns/footer-title-tagline-social.php
  inc/patterns/general-image-with-caption.php
  inc/patterns/general-large-list-names.php
  inc/patterns/general-list-events.php
  inc/patterns/general-video-header-details.php
  inc/patterns/general-video-trailer.php
  inc/patterns/header-centered-logo-black-background.php
  inc/patterns/header-centered-logo.php
  inc/patterns/header-centered-title-navigation-social.php
  inc/patterns/header-default.php
  inc/patterns/header-image-background-overlay.php
  inc/patterns/header-image-background.php
  inc/patterns/header-large-dark.php
  inc/patterns/header-logo-navigation-gray-background.php
  inc/patterns/header-logo-navigation-offset-tagline.php
  inc/patterns/header-logo-navigation-social-black-background.php
  inc/patterns/header-small-dark.php
  inc/patterns/header-stacked.php
  inc/patterns/header-text-only-green-background.php
  inc/patterns/header-text-only-salmon-background.php
  inc/patterns/header-text-only-with-tagline-black-background.php
  inc/patterns/header-title-and-button.php
  inc/patterns/header-title-navigation-social.php
  inc/patterns/header-with-tagline.php
  inc/patterns/hidden-heading-and-bird.php
  inc/patterns/page-about-large-image-and-buttons.php
  inc/patterns/page-about-links-dark.php
  inc/patterns/page-about-links.php
  inc/patterns/page-layout-image-and-text.php
  inc/patterns/page-layout-image-text-and-video.php
  inc/patterns/page-layout-two-columns.php
  inc/patterns/page-sidebar-blog-posts-right.php
  inc/patterns/page-sidebar-blog-posts.php
  inc/patterns/page-sidebar-grid-posts.php
  inc/patterns/page-sidebar-poster.php
  style.css
Labels: [Type] Bug

#301 Add menu container padding
  style.css
Labels: [Type] Enhancement, [Component] Blocks

#320 Add a search template
  templates/search.html
Labels: [Type] Bug

#322 Change Site Title in the footer to a paragraph instead of an H1
  inc/patterns/footer-default.php
Labels: [Type] Regression

#327 Try a static spacer underneath the header
  inc/patterns/header-large-dark.php
  inc/patterns/header-small-dark.php
  parts/header-large-dark.html
  parts/header-small-dark.html
Labels: [Type] Bug

#336 Add negative margins to top-level group and cover blocks
  style.css
Labels: [Type] Bug

#337 Remove extra wrappers from patterns and header templates
  inc/patterns/footer-about-title-logo.php
  inc/patterns/footer-blog.php
  inc/patterns/footer-dark.php
  inc/patterns/footer-logo.php
  inc/patterns/footer-navigation.php
  inc/patterns/footer-query-images-title-citation.php
  inc/patterns/footer-query-title-citation.php
  inc/patterns/footer-title-tagline-social.php
  inc/patterns/header-centered-logo-black-background.php
  inc/patterns/header-centered-logo.php
  inc/patterns/header-centered-title-navigation-social.php
  inc/patterns/header-large-dark.php
  inc/patterns/header-logo-navigation-gray-background.php
  inc/patterns/header-logo-navigation-social-black-background.php
  inc/patterns/header-small-dark.php
  inc/patterns/header-text-only-green-background.php
  inc/patterns/header-text-only-salmon-background.php
  inc/patterns/header-text-only-with-tagline-black-background.php
  parts/header-large-dark.html
  parts/header-small-dark.html
Labels: [Component] Block Templates, [Component] Block Patterns, [Type] Code Quality

#326 Update required WordPress version to 5.9.
  README.md
  readme.txt
  style.css
Labels: [Type] Task
